package cn.eyesw.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.eyesw.lvenxunjian.bean.LatlngEntity;

import cn.eyesw.greendao.LatlngEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig latlngEntityDaoConfig;

    private final LatlngEntityDao latlngEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        latlngEntityDaoConfig = daoConfigMap.get(LatlngEntityDao.class).clone();
        latlngEntityDaoConfig.initIdentityScope(type);

        latlngEntityDao = new LatlngEntityDao(latlngEntityDaoConfig, this);

        registerDao(LatlngEntity.class, latlngEntityDao);
    }
    
    public void clear() {
        latlngEntityDaoConfig.clearIdentityScope();
    }

    public LatlngEntityDao getLatlngEntityDao() {
        return latlngEntityDao;
    }

}
